### ISSUE TITLE
Long-term feature: stop based on desired power

### ISSUE THREAD

**Issue by rbcavanaugh** [rbcavanaugh/pnt#11]
From GF: 

- app could stop based on a researcher's desired power to detect some effect (like change between two administrations)
- to discuss with WH

**Comment by gfergadiotis** [comment]
That is a cool feature...

**Comment by william-hula** [comment]
Yeah, cool idea, but makes me nervous. Seems too much like "we'll just keep collecting data until we get the result we want."

**Comment by gfergadiotis** [comment]
Sure, even though they might conclude that there is no real difference or that the detected difference is so un-important that the cost of treatment does not worth it. In my mind, I was thinking something like a “power surface” similar to power curves but with an extra dimension such as “average SEM as a function of length”.

Having said that, given that this is a whole new project, I suspect now might not be the time to explore it. So, let’s put this in the back burner.

G


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Gerasimos Fergadiotis, PhD., CCC-SLP
Associate Professor
Speech & Hearing Sciences
527 SW Hall Street, RM430G
University Center Building
Portland, OR 97201
Phone: 503-725-2217
Web page: http://aaldresearch.wix.com/aald
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by rbcavanaugh** [comment]
back burner it is!
