### ISSUE TITLE
Need to develop plan for hosting and url and any costs

### ISSUE THREAD

**Issue by rbcavanaugh** [rbcavanaugh/pnt#13]
Questions:
- What is the preferred hosting option?
- Where will $ come from, if used? (perhaps a "https://www.buymeacoffee.com/ account" if no institutional $$ might be successful?)

## Free 

- shinyapps.io free account. We could create a hulaLab account so the URL would be something like https://hulaLab.shinyapps.io/pnt-cat/. This is how the current version is hosted. Easiest to setup and maintain. Note that this is limited to 25 active hours/month. 

## Almost free
- use shinyserver on Amazon/Google cloud using a t2/t3.micro (i.e. very small) instance. This would include a custom URL with a year-cost for the domain (~$10/year). so https://hulaLab.com/pnt-cat. future ACOM app could be https://hulaLab.com/ACOM etc... https://hulaLab.com would host a simple home page we could easily create through markdown. Nice extra features but 

## Monthly $$

- shinyapps.io paid account. $9/mo gets you a little more computing power. $39/mo even more. $99 gets you authentication and $200+/mo gets you a custom domain. probably not worth it considering...
- shiny server on amazon/google/digital ocean cloud using a more powerful instance. Between $10 and $20/mo depending on desired power. Would include custom URL. Could potentially use amazon elastic cloud which would scale the computing power based on user demand. Would need to do a little more research on how the scaling works with EC2. I am currently using digital ocean for my current stuff...its not too bad.

**Comment by rbcavanaugh** [comment]
I will add to this, that whatever solution chosen here should probably be coordinated with a hard fork to the Hula lab or other organizational repo, so that future features can be implemented by future doc students easily

**Comment by gfergadiotis** [comment]
Will mentioned this in one of his most recent emails (something about the VA hosting it..?)
~Will?

**Comment by william-hula** [comment]
Let me ask the VHF about this. They pay for a professional-looking website that we could probably get a free page on: https://veteranshealthfoundation.org/. I have a mildly outdate page here: https://veteranshealthfoundation.org/researchers/william-d-hula-ph-d-ccc-slp/. I assume i could get this modified or maybe get a new page dedicated to the PNT-CAT.

Rob- can you give me any information to inform my question to the VHF? Like, any specs (I don't really know what I'm asking for here) that the contractor who maintains the page would need or want to know?

**Comment by rbcavanaugh** [comment]
Right - the question I suppose then is whether the VHF can provide any cloud computing resources. Most websites are considered static (mostly HTML code) - which is what your current bio on VHF is. Shiny requires a backend server with R installed to perform the calculations under the hood. this is typically done on a virtual Linux server. The typical cloud providers for this kind of thing are amazon web services, google cloud, and digital ocean. I'd be surprised if this was the case, but perhaps worth asking.

**Comment by william-hula** [comment]
Rob- a couple of questions for you:
1. Does knowing that the VHF site is hosted by GoDaddy affect your thinking about how much sense it might make to try to have the app hosted on the VHF site? 
2. The shinyapps.io free account option might serve (25 hours per month equals about 42 full PNTs or 185 PNT-CAT30s), but it's conceivable that it could be limiting. The almost-free "shinyserver on Amazon/Google cloud using a t2/t3.micro (i.e. very small) instance" seems like it could serve well. What would be the benefit of the $9/mo shinyapps.io paid account vs. the shinyserver in the cloud @$10/yr? You mentioned 'a little more computing power'; does that mean more active hours per month, or anything else relevant for the project?

**Comment by rbcavanaugh** [comment]
1. Not really - I don't think that godaddy has cloud computing options, though I could be wrong. 
2. yes the $9/mo shinyapps.io account has 100 hours/month too, sorry I left that out. the $10/year cost for the amazon/google cloud server is mostly a domain name cost - that server could be enough since the app is very simple (as long as its not running any models) and you could always increase the power of the server later on if demand requires it. the cost then would be around the $9/mo. While you get a lot of customization and flexibility with our own cloud server, you do have a occasional maintenance to do (every 6 months, you have to renew the encripted certificate to get the https:: designation)

**Comment by rbcavanaugh** [comment]
Summary from end of July meeting:

We will go with a free shinyapps.io account to start with. Upgrade to the $9 account if necessary

We can always keep the free one so that any pub links work, even if eventually we move it to its own server. 

Closing this issue as resolved.
