### ISSUE TITLE
Responsive and usable on iPad

### ISSUE THREAD

**Issue by rbcavanaugh** [rbcavanaugh/pnt#14]
Many clinicians are using ipads these days. right now, the app looks decent on an iPad (shiny is responsive if done right). However, it requires key-presses to advance. To use the app on an iPad right now, clinicians would need a Bluetooth keyboard. 

Potential solutions:
- create a "tablet mode" where the clinician can hit a correct or incorrect button and a next button on the screen
    - would this affect assessment fidelity? essentially it would/could be providing feedback during testing
    - the buttons could have a response-agnostic icon (e.g. a cat and a fish icon)
    - it could be a single button which could be tapped once or twice with a subtle visual feedback on whether correct or incorrect is selected. 

other ideas?

**Comment by gfergadiotis** [comment]
I agree that providing feedback might be suboptimal. Is it possible to create an app so that the clinician controls the ipad form their phone...?

**Comment by rbcavanaugh** [comment]
Some googling doesn't come up with any pre-built ways to do this. I could imagine a method of saving/querying a database, but I don't think this is a great idea because I don't want to store any data and I suspect it would be complicated to build.

What if the clinician could "swipe" the card left/right or up/down if they're using an iPad? 
https://livefreeordichotomize.com/2017/03/12/introducing-shinyswipr-swipe-your-way-to-a-great-shiny-ui/

**Comment by william-hula** [comment]
Swiping up for correct vs. down for incorrect seems like it could be intuitive for clinicians and sufficiently subtle to avoid giving feedback to most patients. Or is a one-finger vs. two-finger tap a thing?

**Comment by gfergadiotis** [comment]
Swiping (or tapping) sounds like a nice compromise.

**Comment by rbcavanaugh** [comment]
I'd say that it would be like using Tinder but I suspect that might not be helpful. This is good and I'll prioritize this once we have a functioning beta app out

**Comment by rbcavanaugh** [comment]
I'm going to close this for now; will return to it after the beta version come sout.
