### ISSUE TITLE
Option to terminate testing

### ISSUE THREAD

**Issue by gfergadiotis** [rbcavanaugh/pnt#17]
I keep forgetting to bring this up. Would it be possible to allow the clinician to terminate testing and have the app print the results up until that point? That would be very convenient in a number of cases.

**Comment by rbcavanaugh** [comment]
Sure, good idea.  a couple of questions:

- should this be available regardless of the testing type? (IRT, full pnt, Walker short form)

- should it come with a warning (especially for IRT forms) that says something like "warning, ending early may reduce the accuracy and precision of participant naming ability"?

**Comment by rbcavanaugh** [comment]
Actually, this was super easy to do. Now, if you hit the 'esc' key during testing, an alert will pop up asking if you would like to end the test early, and the user can hit "confirm" to skip to the last page where data can be downloaded. 

Please add any comments for any additional language for ending the test early. The escape key seemed to be the easiest way to let the user stop the test early. I can add a button to the page itself, but getting it to stay in one place fixed on the screen can be finicky with different screen sizes.

**Comment by rbcavanaugh** [comment]
Alex: clarify language around confirmed responses -
